### ISSUE TITLE
Perhaps the "known" world of sample code should be "address"

### ISSUE THREAD

**Issue by masstensor** [helium/angry-purple-tiger-rs#5]
use angry_purple_tiger::AnimalName;

let address = "112CuoXo7WCcp6GGwDNBo6H5nKXGH45UNJ39iEefdv2mwmnwdFt8";
let animal_name = **known**.parse::<AnimalName>().expect("animal name");
assert_eq!(animal_name, "feisty-glass-dalmatian")

**Comment by madninja** [comment]
> use angry_purple_tiger::AnimalName;
> 
> let address = "112CuoXo7WCcp6GGwDNBo6H5nKXGH45UNJ39iEefdv2mwmnwdFt8"; let animal_name = **known**.parse::().expect("animal name"); assert_eq!(animal_name, "feisty-glass-dalmatian")

you're asking if  it should be

```
let animal_name = known.parse::().expect("animal name");
```

instead of

```
let animal_name = address.parse::().expect("animal name");
```

If so that seems like a personal preference?

**Comment by masstensor** [comment]
yeah, I think "known" is a typo, it should be replace with "address".

**Comment by madninja** [comment]
sure.. want to submit a PR?

**Comment by masstensor** [comment]
It seems that I have no permission to submit a PR...

**Comment by madninja** [comment]
You fork the repo and do a PR from your fork

**Comment by masstensor** [comment]
OK, i have create a pull request, please review it, thanks.
