### ISSUE TITLE
Duplicate attribute and animal entries 

### ISSUE THREAD

**Issue by sunsided** [helium/angry-purple-tiger-rs#8]
The adjectives list contains duplicates of the words `skinny`, `short`, `long`, `cool`, `hot` and `tangy`.
The animal list contains duplicates of the word `tiger`, `mammoth` and `raccoon`.
The word `swift` is used both as an adjective and animal name.

The JavaScript implementation has the same issue - I originally opened that issue at helium/angry-purple-tiger#6.

**Comment by madninja** [comment]
Closing as known but not fixable
